-- 2단계: 자료를 코드 밖으로 옮깁니다
-- Supabase Table 및 RLS 설정, 가상 메모 세 건 이전

-- 1. notes 테이블 생성 (owner_id는 uuid 형식이며 auth.users 외래키는 연결하지 않음)
create table if not exists notes (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  owner_id uuid,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- 2. RLS (Row Level Security) 활성화
alter table notes enable row level security;

-- 3. anon 및 authenticated 역할에 자료 읽기(SELECT) 권한을 부여하지 않음
revoke select on table notes from anon, authenticated;
